package com.example.FrankySabado.ayudas;

public enum Especialidad {

    DESARROLLO_BACKEND,
    DESARROLLO_FRONTEND,
    ARQUITECTURA_SOFTWARE,
    INGENIERIA_DATOS,
    CIENCIA_DATOS,
    SEGURIDAD_INFORMATICA,
    DEVOPS,
    QA_AUTOMATIZADO,
    QA_MANUAL,
    ADMINISTRACION_BD,
    ANALISIS_NEGOCIOS,
    GESTION_PROYECTOS,
    INTELIGENCIA_ARTIFICIAL,
    MACHINE_LEARNING,
    CLOUD_COMPUTING,
    INTERNET_DE_LAS_COSAS,
    REALIDAD_VIRTUAL,
    DESARROLLO_MOVIL,
    INTEGRACION_APIS,
    SOPORTE_TECNICO

}
